In [1]:
import pandas as pd
import numpy as np
from pyDecision.algorithm import ahp_method

In [2]:
df = pd.read_csv('/home/math/Downloads/webmedia_2022-main (1)/datasets/filtered_dataset_gas.csv')

In [3]:
#indexes crime, accidents, nature, attraction, duration, traffic, length and pollution
decision_matrix = [[1,3,7,7,5,1,1,3],          
                   [0.33,1,7,7,1,2,2,3],        
                   [0.14,0.14,1,2,0.2,0.2,0.14,0.5],
                   [0.14,0.14,0.5,1,0.14,0.2,0.11,0.2],
                   [0.2,1,5,7,1,0.33,1,3],
                   [1, 0.5, 5, 5, 3, 1, 1, 1],
                   [1,0.5, 7, 9, 1, 1, 1, 1],
                   [0.33, 0.33, 2, 5, 0.33, 1, 1, 1]]

decision_matrix_worker = [[1,0.33,3,3,0.14,0.14,0.11,3],
                          [3,1,3,3,0.14,0.14,0.14,3],
                          [0.33,0.33,1,1,0.11,0.11,0.11,0.33],
                          [0.33,0.33,1,1,0.11,0.11,0.11,0.33],
                          [7,7,9,9,1,2,0.5,9],
                          [7,7,9,9,0.5,1,0.5,9],
                          [9,7,9,9,2,2,1,9],
                          [0.33,0.33,3,3,0.14,0.11,0.11,1]]

decision_matrix_green = [[1,3,0.14,3,3,1,1,0.14],
                         [0.33,1,0.14,0.33,3,0.33,1,0.14],
                         [7,7,1,7,7,3,3,0.5],
                         [0.33,3,0.14,1,3,3,3,0.2],
                         [0.33,0.33,0.14,0.33,1,1,0.5,0.14],
                           [1,3,0.33,0.33,1,1,0.5,0.14],
                           [1,1,0.33,0.33,2,2,1,0.14],
                           [7,7,2,5,7,7,7,1]]

decision_matrix_safer = [[1,3,7,7,5,5,5,7],
                         [0.33,1,9,7,5,3,5,5],
                         [0.14,0.11,1,1,0.2,0.2,0.33,0.33],
                         [0.14,0.14,1,1,0.2,0.2,0.2,0.2],
                         [0.2,0.2,5,5,1,0.33,3,0.5],
                         [0.2,0.33,5,5,3,1,5,2],
                         [0.2,0.2,3,5,0.33,0.2,1,0.2],
                         [0.14,0.2,3,5,2,0.5,5,1]]


In [4]:
weight_derivation = 'geometric'

#weights, rc = ahp_method(decision_matrix, wd = weight_derivation)

#for i in range (0, weights.shape[0]):
    #print('w(g'+str(i+1)+'): ',round(weights[i], 3))

#weights worker

weights_w,rc_w = ahp_method(decision_matrix_worker, wd = weight_derivation)

for i in range (0, weights_w.shape[0]):
    print ('w_w(feature '+str(i+1)+'): ',round(weights_w[i],3))

#consistency ratio worker

print('RC_worker: ' + str(round(rc_w, 2)))
if (rc_w > 0.1):
    print('The solution is inconsistent, pairwise comparison must be reviewed')
else:
    print('The solution is consistent')


w_w(feature 1):  0.044
w_w(feature 2):  0.06
w_w(feature 3):  0.021
w_w(feature 4):  0.021
w_w(feature 5):  0.268
w_w(feature 6):  0.225
w_w(feature 7):  0.329
w_w(feature 8):  0.032
RC_worker: 0.07
The solution is consistent


In [5]:
#weights green

weights_g,rc_g = ahp_method(decision_matrix_green, wd = weight_derivation)

for i in range (0, weights_g.shape[0]):
    print ('w_g(feature '+str(i+1)+'): ',round(weights_g[i],3))

#consistency ratio green

print('RC_green: ' + str(round(rc_g, 2)))
if (rc_g > 0.1):
    print('The solution is inconsistent, pairwise comparison must be reviewed')
else:
    print('The solution is consistent')

w_g(feature 1):  0.079
w_g(feature 2):  0.039
w_g(feature 3):  0.272
w_g(feature 4):  0.082
w_g(feature 5):  0.032
w_g(feature 6):  0.053
w_g(feature 7):  0.06
w_g(feature 8):  0.383
RC_green: 0.09
The solution is consistent


In [6]:
#weights_safer

weights_s,rc_s = ahp_method(decision_matrix_safer, wd = weight_derivation)

for i in range (0, weights_s.shape[0]):
    print ('w_s(feature '+str(i+1)+'): ',round(weights_s[i],3))

#consistency ratio safer

print('RC_safer: ' + str(round(rc_s, 2)))
if (rc_s > 0.1):
    print('The solution is inconsistent, pairwise comparison must be reviewed')
else:
    print('The solution is consistent')


w_s(feature 1):  0.357
w_s(feature 2):  0.252
w_s(feature 3):  0.025
w_s(feature 4):  0.022
w_s(feature 5):  0.075
w_s(feature 6):  0.134
w_s(feature 7):  0.045
w_s(feature 8):  0.09
RC_safer: 0.09
The solution is consistent


In [7]:
user_test = df[df['setID'] == 56.0]
weights_w

array([0.04408469, 0.0598695 , 0.02083589, 0.02083589, 0.26789367,
       0.22527083, 0.32874792, 0.0324616 ])

In [8]:
weights_g

array([0.07864944, 0.03943284, 0.27192161, 0.08213207, 0.03152021,
       0.05310667, 0.0600337 , 0.38320346])

In [9]:
weights_s

array([0.35730536, 0.2516863 , 0.02470017, 0.02246057, 0.07519683,
       0.13372097, 0.04484505, 0.09008475])

In [10]:
decision_matrix_ldt = [[1,0.33,5],
                       [3,1,7],
                       [0.2,0.14,1]]

decision_matrix_lpn = [[1,0.25,0.5],
                       [4,1,5],
                       [2,0.2,1]]

decision_matrix_lca = [[1,0.25,0.33],
                       [4,1,3],
                       [3,0.33,1]]

In [11]:
#weights_(length,duration,traffic)
weights_ldt,rc_ldt = ahp_method(decision_matrix_ldt, wd = weight_derivation)

for i in range(0, weights_ldt.shape[0]):
    print('w_ldt(g'+str(i+1)+'): ', round(weights_ldt[i], 3))

#consistency_ratio_ldt
print('RC: ' + str(round(rc_ldt, 2)))
if (rc_ldt > 10):
    print('The solution is inconsistent, the pairwise comparisons must be reviewed')
else:
    print('The solution is consistent')

w_ldt(g1):  0.278
w_ldt(g2):  0.65
w_ldt(g3):  0.072
RC: 0.05
The solution is consistent


In [12]:
#weights_(length,pollution,nature)
weights_lpn,rc_lpn = ahp_method(decision_matrix_lpn, wd = weight_derivation)

for i in range(0, weights_lpn.shape[0]):
    print('w_lpn(g'+str(i+1)+'): ', round(weights_lpn[i], 3))

#consistency_ratio_lpn
print('RC: ' + str(round(rc_lpn, 2)))
if (rc_lpn > 10):
    print('The solution is inconsistent, the pairwise comparisons must be reviewed')
else:
    print('The solution is consistent')

w_lpn(g1):  0.127
w_lpn(g2):  0.687
w_lpn(g3):  0.186
RC: 0.08
The solution is consistent


In [13]:
#weights_(length,crime,accident)
weights_lca,rc_lca = ahp_method(decision_matrix_lca, wd = weight_derivation)

for i in range(0, weights_lca.shape[0]):
    print('w_lca(g'+str(i+1)+'): ', round(weights_lca[i], 3))

#consistency_ratio_lca
print('RC: ' + str(round(rc_lca, 2)))
if (rc_lca > 10):
    print('The solution is inconsistent, the pairwise comparisons must be reviewed')
else:
    print('The solution is consistent')

w_lca(g1):  0.117
w_lca(g2):  0.615
w_lca(g3):  0.268
RC: 0.06
The solution is consistent


In [14]:
weights_ldt

array([0.27841576, 0.65003827, 0.07154597])

In [15]:
weights_lpn

array([0.12654307, 0.68698147, 0.18647546])

In [16]:
weights_lca

array([0.11697958, 0.61520403, 0.26781639])

In [17]:
user_test

ID  crimeNorm  accidentNorm  natureNorm  attractionNorm  durationNorm  \
18  294.0   1.000000      1.000000    0.837039             0.0      0.985915   
19  295.0   0.920751      0.714286    0.725042             0.0      1.000000   
20  296.0   0.922930      0.464286    0.788357             0.0      0.777465   
21  297.0   0.979953      0.000000    0.968940             0.0      0.000000   
22  298.0   0.837111      0.339286    1.000000             1.0      0.873239   
23  299.0   0.525019      1.000000    0.000000             0.0      0.816901   
24  300.0   0.000000      0.142857    0.401910             0.0      0.309859   

    trafficNorm  lengthNorm  setID    crimes  accidents  attractions  \
18     1.000000    0.677271   56.0  159309.0       12.0          0.0   
19     0.715349    0.661670   56.0  175533.0       28.0          0.0   
20     0.747426    0.489140   56.0  175087.0       42.0          0.0   
21     0.116428    0.446620   56.0  163413.0       68.0          0.0   
22     0.491951    0.000000   56.0  192656.0       49.0          1.0   
23     0.876536    0.934842   56.0  256548.0       12.0          0.0   
24     0.000000    1.000000   56.0  364031.0       60.0          0.0   

           nature   traffic  duration   length  \
18  290542.753787  0.945144    1112.0   9044.0   
19  258559.537764  0.902439    1107.0   9095.0   
20  276640.563218  0.907251    1186.0   9659.0   
21  328209.585576  0.812585    1462.0   9798.0   
22  337079.532796  0.868924    1152.0  11258.0   
23   51509.146338  0.926621    1172.0   8202.0   
24  166282.854367  0.795118    1352.0   7989.0   

                                          coordinates   polution  polutionNorm  
18  0.01641:51.43737;0.01765:51.43787;0.0176:51.43...  25.192857      0.023417  
19  0.01641:51.43737;0.01765:51.43787;0.0176:51.43...  25.190813      0.024077  
20  0.01641:51.43737;0.01765:51.43787;0.0176:51.43...  25.164875      0.032446  
21  0.01641:51.43737;0.01765:51.43787;0.0176:51.43...  24.067055      0.386669  
22  0.01641:51.43737;0.01765:51.43787;0.0176:51.43...  25.265432      0.000000  
23  0.01641:51.43737;0.01765:51.43787;0.01775:51.4...  24.861210      0.130426  
24  0.01641:51.43737;0.01765:51.43787;0.0176:51.43...  22.166197      1.000000

In [18]:
df

ID  crimeNorm  accidentNorm  natureNorm  attractionNorm  \
0      30.0   0.920527      0.924528    0.212596        0.000000   
1      31.0   1.000000      0.490566    0.051620        0.000000   
2      32.0   0.974080      0.471698    0.688265        0.000000   
3      33.0   0.172486      1.000000    0.152550        0.500000   
4      34.0   0.000000      0.924528    0.000000        1.000000   
..      ...        ...           ...         ...             ...   
665  3158.0   0.865327      0.905172    0.000000        0.454545   
666  3159.0   1.000000      1.000000    0.069511        0.000000   
667  3160.0   0.000000      0.482759    1.000000        0.363636   
668  3161.0   0.191761      0.327586    0.284930        0.727273   
669  3162.0   0.094392      0.000000    0.059355        1.000000   

     durationNorm  trafficNorm  lengthNorm  setID     crimes  accidents  \
0        1.000000     0.889155    0.428035    7.0   310580.0       61.0   
1        0.995633     1.000000    1.000000    7.0   298705.0       84.0   
2        0.877729     0.407789    0.776387    7.0   302578.0       85.0   
3        0.000000     0.866310    0.000000    7.0   422353.0       57.0   
4        0.344978     0.771865    0.095953    7.0   448126.0       61.0   
..            ...          ...         ...    ...        ...        ...   
665      1.000000     0.952936    1.000000  598.0   945244.0      157.0   
666      0.984866     1.000000    0.914072  598.0   890976.0      146.0   
667      0.000000     0.000000    0.000000  598.0  1293936.0      206.0   
668      0.176950     0.343876    0.511234  598.0  1216664.0      224.0   
669      0.231665     0.227897    0.662594  598.0  1255900.0      262.0   

     attractions         nature   traffic  duration   length  \
0            0.0  837166.117353  0.936039    1454.0  18727.0   
1            0.0  823320.786870  0.945704    1455.0  17356.0   
2            0.0  878077.719383  0.894062    1482.0  17892.0   
3            1.0  832001.606618  0.934046    1683.0  19753.0   
4            2.0  818881.017743  0.925810    1604.0  19523.0   
..           ...            ...       ...       ...      ...   
665          9.0  527463.871935  0.862765    1982.0  13369.0   
666          4.0  541806.384165  0.873684    1995.0  13587.0   
667          8.0  733799.038202  0.641675    2841.0  15906.0   
668         12.0  586254.998908  0.721458    2689.0  14609.0   
669         15.0  539710.909985  0.694550    2642.0  14225.0   

                                           coordinates   polution  \
0    -0.2677:51.533778;-0.2677:51.53326;-0.26763:51...  35.750511   
1    -0.2677:51.533778;-0.2677:51.53326;-0.26763:51...  34.997732   
2    -0.2677:51.533778;-0.2677:51.53326;-0.26763:51...  34.748889   
3    -0.2677:51.533778;-0.2677:51.53326;-0.26763:51...  33.829126   
4    -0.2677:51.533778;-0.2677:51.53326;-0.26763:51...  33.815324   
..                                                 ...        ...   
665  -0.073976:51.470078;-0.07394:51.46994;-0.07388...  30.705686   
666  -0.073976:51.470078;-0.07404:51.47032;-0.07423...  30.809028   
667  -0.073976:51.470078;-0.07394:51.46994;-0.07388...  31.710485   
668  -0.073976:51.470078;-0.07404:51.47032;-0.07423...  28.795455   
669  -0.073976:51.470078;-0.07394:51.46994;-0.07388...  29.156357   

     polutionNorm  
0        0.177211  
1        0.497272  
2        0.603073  
3        0.994132  
4        1.000000  
..            ...  
665      0.344696  
666      0.309245  
667      0.000000  
668      1.000000  
669      0.876192  

[670 rows x 19 columns]

In [19]:
#worker
def evaluate_routes(routes, weights_w, columns):
    routes_parameters = routes[columns[1:]]
    results_array = []
    result = 0
    for route in routes_parameters.iterrows():
        result = np.multiply(np.array(route[1]), np.array(weights_w))
        results_array.append(np.sum(result))
    #print(results_array)
    return results_array

columns = ['ID', 'crimeNorm', 'accidentNorm', 'natureNorm', 'attractionNorm', 'durationNorm',
           'trafficNorm', 'lengthNorm', 'polutionNorm']


evaluate_routes(user_test, weights_w, columns)


[0.8341977031545686,
 0.7458071526091548,
 0.6234179524213149,
 0.2489946608524331,
 0.44364602409876425,
 0.8108769395897414,
 0.4611457798024384]

In [20]:
#green
def evaluate_routes(routes, weights_g, columns):
    routes_parameters = routes[columns[1:]]
    results_array = []
    result = 0
    for route in routes_parameters.iterrows():
        result = np.multiply(np.array(route[1]), np.array(weights_g))
        results_array.append(np.sum(result))
    print(results_array)
    return results_array

columns = ['ID', 'crimeNorm', 'accidentNorm', 'natureNorm', 'attractionNorm', 'durationNorm',
           'trafficNorm', 'lengthNorm', 'polutionNorm']

evaluate_routes(user_test, weights_g, columns)

[0.47950686099333306, 0.41619615825276174, 0.411264746728797, 0.521716444889885, 0.48692156612185683, 0.2591260440119013, 0.5679253745447104]


[0.47950686099333306,
 0.41619615825276174,
 0.411264746728797,
 0.521716444889885,
 0.48692156612185683,
 0.2591260440119013,
 0.5679253745447104]

In [21]:
#safer
def evaluate_routes(routes, weights_s, columns):
    routes_parameters = routes[columns[1:]]
    results_array = []
    result = 0
    for route in routes_parameters.iterrows():
        result = np.multiply(np.array(route[1]), np.array(weights_s))
        results_array.append(np.sum(result))
    print(results_array)
    return results_array

columns = ['ID', 'crimeNorm', 'accidentNorm', 'natureNorm', 'attractionNorm', 'durationNorm',
           'trafficNorm', 'lengthNorm', 'polutionNorm']

evaluate_routes(user_test, weights_s, columns)

[0.8700071434061504, 0.7293694907292592, 0.6493623721127327, 0.4445060149284603, 0.5631075379208146, 0.6715906600482953, 0.20411266426505326]


[0.8700071434061504,
 0.7293694907292592,
 0.6493623721127327,
 0.4445060149284603,
 0.5631075379208146,
 0.6715906600482953,
 0.20411266426505326]

In [22]:
#ldt
def evaluate_routes(routes, weights_ldt, columns_ldt):
    routes_parameters = routes[columns_ldt[1:]]
    results_array = []
    result = 0
    for route in routes_parameters.iterrows():
        result = np.multiply(np.array(route[1]), np.array(weights_ldt))
        results_array.append(np.sum(result))
    print(results_array)
    return results_array

columns_ldt = ['ID', 'lengthNorm', 'durationNorm', 'trafficNorm']

evaluate_routes(user_test, weights_ldt, columns_ldt)

[0.900991786200466, 0.8854380592317804, 0.6950415513032885, 0.13267592481732068, 0.6028361918064982, 0.8540046839857318, 0.47983606727822037]


[0.900991786200466,
 0.8854380592317804,
 0.6950415513032885,
 0.13267592481732068,
 0.6028361918064982,
 0.8540046839857318,
 0.47983606727822037]

In [23]:
#lpn
def evaluate_routes(routes, weights_lpn, columns_lpn):
    routes_parameters = routes[columns_lpn[1:]]
    results_array = []
    result = 0
    for route in routes_parameters.iterrows():
        result = np.multiply(np.array(route[1]), np.array(weights_lpn))
        results_array.append(np.sum(result))
    print(results_array)
    return results_array

columns_lpn = ['ID', 'lengthNorm', 'polutionNorm', 'natureNorm']

evaluate_routes(user_test, weights_lpn, columns_lpn)

[0.2578783467003911, 0.23547248951940947, 0.23119631565294496, 0.5028342191374807, 0.18647546059949716, 0.20789837184166488, 0.8884709662162056]


[0.2578783467003911,
 0.23547248951940947,
 0.23119631565294496,
 0.5028342191374807,
 0.18647546059949716,
 0.20789837184166488,
 0.8884709662162056]

In [24]:
#lca
def evaluate_routes(routes, weights_lca, columns_lca):
    routes_parameters = routes[columns_lca[1:]]
    results_array = []
    result = 0
    for route in routes_parameters.iterrows():
        result = np.multiply(np.array(route[1]), np.array(weights_lca))
        results_array.append(np.sum(result))
    print(results_array)
    return results_array

columns_lca = ['ID', 'lengthNorm', 'crimeNorm', 'accidentNorm']

evaluate_routes(user_test, weights_lca, columns_lca)

[0.9622473354548298, 0.8351490940073469, 0.7493527907474696, 0.6551166110511848, 0.6058602184317532, 0.7001678555158772, 0.15523906763280482]


[0.9622473354548298,
 0.8351490940073469,
 0.7493527907474696,
 0.6551166110511848,
 0.6058602184317532,
 0.7001678555158772,
 0.15523906763280482]